# Generated by Django 5.2.6 on 2025-10-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='combates_empatados',
        ),
    ]
