# Generated by Django 5.2.6 on 2025-10-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_remove_usuario_combates_empatados'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='combates_empatados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
