# Generated by Django 5.2.6 on 2025-10-09 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokedex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pokemon_enemigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_enemigo', to='pokedex.pokemon')),
                ('pokemon_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_usuario', to='pokedex.pokemon')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
