# Generated by Django 5.2.6 on 2025-10-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gimnasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('lider', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokebola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(max_length=30)),
                ('debilidad', models.CharField(max_length=30)),
                ('ataque1', models.CharField(max_length=50)),
                ('ataque2', models.CharField(max_length=50)),
                ('imagen_frente', models.ImageField(blank=True, null=True, upload_to='pokemones/')),
                ('imagen_espalda', models.ImageField(blank=True, null=True, upload_to='pokemones/')),
            ],
        ),
    ]
