# Generated by Django 5.2.6 on 2025-09-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gimnasio',
            old_name='nombre_lider',
            new_name='lider',
        ),
    ]
