# Generated by Django 5.2.6 on 2025-10-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entrenadores/'),
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='gimnasios/'),
        ),
        migrations.AddField(
            model_name='pokebola',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pokebolas/'),
        ),
    ]
