# Generated by Django 5.2.6 on 2025-10-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_entrenador_imagen_gimnasio_imagen_pokebola_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gimnasio',
            name='nombre',
        ),
    ]
